matrix:
  include:
    - os: osx
    - os: linux

osx_image: xcode8.1

addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - yasm
    - libunwind8

install:
- pip install --user azure-cli
- ./download.sh
- ./install-dotnet-$TRAVIS_OS_NAME.sh

script:
- ./build.sh
- ./package.sh

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then az=$HOME/.local/bin/az; fi
- $az storage blob upload -f FFmpeg.Native.H264/bin/Release/FFmpeg.Native.H264.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg -c ffmpeg -n FFmpeg.Native.H264.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg
