matrix:
  include:
    - os: osx
      osx_image: xcode8.1
    - os: linux
      env: CROSS=yes

addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - yasm
    - libunwind8

install:
- ./download.sh
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yasm; fi
- ./install-dotnet-$TRAVIS_OS_NAME.sh

script:
- ./build.sh
- ./package.sh

after_success:
-  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ~/dotnet/dotnet nuget push FFmpeg.Native.H264/bin/Release/FFmpeg.Native.H264.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg -s nuget.org -k $NUGET_KEY; fi
-  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ~/dotnet/dotnet nuget push runtime.win7-x64.FFmpeg.Native.H264/bin/Release/runtime.win7-x64.FFmpeg.Native.H264.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg -s nuget.org -k $NUGET_KEY; fi
-  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ~/dotnet/dotnet nuget push runtime.osx-x64.FFmpeg.Native.H264/bin/Release/runtime.osx-x64.FFmpeg.Native.H264.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg -s nuget.org -k $NUGET_KEY; fi
