matrix:
  include:
    - os: osx
      osx_image: xcode8.1
    - os: linux
      env: CROSS=yes CUVID=yes
    - os: linux
      env: CROSS=no CUVID=no

addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - yasm
    - libunwind8

install:
- ./download.sh
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yasm; fi
- ./install-dotnet-$TRAVIS_OS_NAME.sh

script:
- ./build.sh
- ./package.sh

after_success:
-  if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CROSS" == "yes" ]] ; then ~/dotnet/dotnet nuget push FFmpeg.Native.H264/bin/Release/FFmpeg.Native.H264.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg -s nuget.org -k $NUGET_KEY; fi
-  if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CROSS" == "yes" ]]; then ~/dotnet/dotnet nuget push FFmpeg.Native.H264.win7-x64/bin/Release/FFmpeg.Native.H264.win7-x64.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg -s nuget.org -k $NUGET_KEY; fi
-  if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CROSS" == "no" ]]; then ~/dotnet/dotnet nuget push FFmpeg.Native.H264.linux-x64/bin/Release/FFmpeg.Native.H264.linux-x64.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg -s nuget.org -k $NUGET_KEY; fi
-  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ~/dotnet/dotnet nuget push FFmpeg.Native.H264.osx-x64/bin/Release/FFmpeg.Native.H264.osx-x64.1.0.0-r$TRAVIS_BUILD_NUMBER.nupkg -s nuget.org -k $NUGET_KEY; fi
