jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  variables:
    FFMPEG_VERSION: "3.3.4"
  container:
    image: ubuntu:18.04
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - script: |
      sudo apt-get install -y build-essential gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 yasm libunwind8 wget
    displayName: Install cross-compiler
  - script: |
      wget -nv -nc http://ffmpeg.org/releases/ffmpeg-$(FFMPEG_VERSION).tar.bz2 -O ffmpeg-$(FFMPEG_VERSION).tar.bz2
      tar xjf ffmpeg-$(FFMPEG_VERSION).tar.bz2
    displayName: Download FFmpeg
  - script: |
      # See https://github.com/FFmpeg/FFmpeg/blob/master/configure for an overview of all configuration
      # options
      ./configure --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --disable-static --enable-shared --enable-version3 --enable-cuda --enable-cuvid --enable-dxva2
      make
    workingDirectory: ffmpeg-$(FFMPEG_VERSION)
    displayName: Build FFmpeg
  - script:
      make DESTDIR=$(Build.ArtifactStagingDirectory) install
    workingDirectory: ffmpeg-$(FFMPEG_VERSION)
    displayName: Install FFmpeg
  - script:
      cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll $(Build.ArtifactStagingDirectory)
    displayName: Copy additional libraries
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: ffmpeg